version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    timezone: Europe/Amsterdam
  open-pull-requests-limit: 10
  assignees:
  - mjwsteenbergen
  ignore:
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.9.1
